---
- name: Deploy application
  hosts: localhost
  become: true
  tasks:
    - name: Ensure the project directory exists
      file:
        path: /var/www/wordpress/wp-content/themes/barbariscatalogfirst
        state: .
        owner: www-data
        group: www-data

    - name: Copy project files
      copy:
        src: .
        dest: /var/www/wordpress/wp-content/themes/barbariscatalogfirst
        owner: www-data
        group: www-data

    - name: Restart web server
      service:
        name: nginx
        state: restarted