name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy project
    permissions:
      deployments: write
    runs-on: self-hosted      
    
    steps:
      - name: Set up SSH Key and Deploy my App on Server
        uses: appleboy/ssh-action@master
          
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
           
          port: 22
          script: |
            echo "Current directory: $(pwd)"
            ls
            cd /var/www/wordpress/wp-content/themes/barbariscatalogfirst
            echo "Current directory: $(pwd)"
            git pull origin main
           