name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy project
    permissions:
      deployments: write
    runs-on: self-hosted
    
    steps:
      - name: Set up SSH Key and Deploy my App on Server
        uses: appleboy/ssh-action@master
          
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
           
          
          run: |
            git config --global user.name "RuslanKharisov"
            git config --global user.email "ruslan.kharisov@gmail.com.com"
            echo "Checking for updates or initializing Git..."
            cd /var/www/wordpress/wp-content/themes/barbariscatalogfirst
            git init if [ ! -d .git ]
            git fetch --prune
            git reset --hard origin/main