name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy project
    permissions:
      deployments: write
    runs-on: self-hosted
    
    steps:
      - name: Set up SSH Key and Deploy my App on Server
        uses: appleboy/ssh-action@master
          
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
           
          port: 22
          script: |
            echo "Checking for updates..."
            ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $REMOTE_USER@$REMOTE_HOST 'cd /var/www/wordpress/wp-content/themes/barbariscatalogfirst && git fetch origin main'
            echo "Pulling changes..."
            ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $REMOTE_USER@$REMOTE_HOST 'cd /var/www/wordpress/wp-content/themes/barbariscatalogfirst && git reset --hard origin/main'
           