name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Deploy to VPS using Ansible
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          echo "Current directory: $(pwd)"
          ansible-playbook -v -i ../../ansible/inventory ../../ansible/site.yml
        env:
          ARGS: "-avzr --delete"
          SOURCE: "../../"
          TARGET: "/var/www/wordpress/wp-content/themes/barbariscatalogfirst"
